
% This is an example of a pre-processing pipeline for multiple subjects 
% using subject the function eega_RunAll
% This function runs a series of function for all the files found in the
% input folder with a name adhering to the inputname
% Usage
% eega_RunAll( Infputname,inputfolder, outpurfolder, function_i, parameters_i, 'prename','xx_','runto', 1);

clear, close all
restoredefaultpath
clc

%% ------------------------------------------------------------------------
%% PATHS
% Folder where EEGLAB is
Path2Mat1 = 'C:\Users\an251296\Documents\MATLAB\toolbox\eeglab14_0_0b';
% Folder where the function eega_ are
Path2Mat2 = 'C:\Users\an251296\nextCloud\MATLAB\mytoolbox\eega_v6_used';
% Folder where the data is and will be saved
Path2Data = 'C:\Users\an251296\nextCloud\MATLAB\mytoolbox\eega_v6_used\examples\DATA';
% Folder where the event files are
Path2DataEvent = 'C:\Users\an251296\nextCloud\MATLAB\mytoolbox\eega_v6_used\examples\DATA\evt';
% Current path
Path0 = 'C:\Users\an251296\nextCloud\MATLAB\mytoolbox\eega_v6_used\examples';
% Channels location file
filechanloc128 = fullfile(Path0, 'ElectrodesLayout','GSN-HydroCel-128.sfp');

%% ------------------------------------------------------------------------
%% ADD TOOLBOXES
% add EEGLAB
cd(Path2Mat1)
eeglab
close all
% Add the functions
addpath(genpath(Path2Mat2))
% Add the path to the data
addpath(genpath(fullfile(Path2Data)))
% Got to the original path
cd(Path0)
% Add the path to the folder with the parameters
addpath(fullfile(Path0, 'parameters'))


%% ------------------------------------------------------------------------
%% IMPORT DATA AND INFORMATION OF THE EVENTS

Path2DataRaw = fullfile(Path2Data, 'raw');
Path2DataMFF = fullfile(Path2Data, 'mff');
OutputFolder = fullfile(Path2Data, 'set'); 

% OPTION 1: import .raw files and .evt event files
eega_RunAll( 'Session*.raw',...
    Path2DataRaw,...
    OutputFolder,...
    'eega_importdata', {},...
    'eega_importinfoevents', {Path2DataEvent},...
    'eega_addchinfo', {filechanloc128, 'filetype', 'sfp'},...
    'eega_rmvcloseeventsB', {'DIN1', 0.500, 0},...
    'prename','','runto', 1);

% % OPTION 2: import .raw files and .evt event files
%  eega_RunAll( 'Session*.raw',...
%     Path2DataMFF,...
%     OutputFolder,...
%     'eega_importdata', {},...
%     'eega_addeventsfromevt', {Path2DataEvent, 4},...
%     'eega_eventextra2fields', {[],'%d'},...
%     'eega_addchinfo', {filechanloc128, 'filetype', 'sfp'},...
%     'eega_rmvcloseeventsB', {'DIN1', 0.500, 0},...
%     'prename','','runto', 1);
        
%% ------------------------------------------------------------------------
%% ARTIFACTS DETECTION AND CORRECTION ON CONTINUOS DATA

InputFolder = fullfile(Path2Data, 'set'); 
OutputFolder = fullfile(Path2Data, 'art'); 

ex_parameters_preprocessing     % the parameters 
filt_highpass = 0.2;
filt_lowpass = 40;
minphase = 0;

eega_RunAll( 'Session*.set',...
    InputFolder,...
    OutputFolder,...
    'eega_addchinfo',               {filechanloc128, 'filetype', 'sfp'},...
    'eega_demean',                  {},...
    'pop_eegfiltnew',               {[], filt_lowpass,  [], 0, [], [], minphase},...
    'pop_eegfiltnew',               {filt_highpass, [], [], 0, [], [], minphase},...
    'eega_tArtifacts',              {ArtPwrS, 'FilterDo', 0, 'KeepRejPre', 0},...
    'eega_tArtifacts',              {ArtMot1, 'FilterDo', 1, 'KeepRejPre', 1},...
    'eega_tArtifacts',              {ArtJump, 'FilterDo', 1, 'KeepRejPre', 1},...
    'eega_tDefBTBC',                {BTall.nbc,BCall.nbt,BCall.nbt,'keeppre',0,'minBadTime',BTall.minBadTime,'minGoodTime',BTall.minGoodTime,'maskTime',BTall.maskTime},...
    'eega_tTargetPCAxElEEG',        {Int.PCA.nSV, Int.PCA.vSV, 'maxTime', Int.PCA.maxTime,'maskTime', Int.PCA.maskTime,'splicemethod', Int.PCA.splicemethod, 'wsize', Int.PCA.wsize, 'order', Int.PCA.order},...
    'eega_tDefBTBC',                {BTall.nbc,BCall.nbt,BCall.nbt,'keeppre',0,'minBadTime',BTall.minBadTime,'minGoodTime',BTall.minGoodTime,'maskTime',BTall.maskTime},...
    'eega_tInterpSpatialSegmentEEG',{Int.Spl.p,'pneigh',Int.Spl.pneigh,'splicemethod',Int.Spl.splicemethod,'mingoodtime',Int.Spl.minGoodTime,'minintertime',Int.Spl.minInterTime,'masktime',Int.Spl.maskTime},...
    'prename','is_a_fh2e-01_fl40_','runto', 2);

% interpolate bad channels + artifacts
eega_RunAll( 'is_a_fh2e-01_fl40_Session*.set',...
    fullfile(Pprp, Pdata, 'art'),...
    fullfile(Pprp, Pdata, 'art'),...
    'eega_tInterpSpatialEEG',       {Int.Spl.p,'pneigh',Int.Spl.pneigh},...
    'eega_tArtifacts',              {ArtMot2, 'FilterDo', 1, 'KeepRejPre', 1},...
    'eega_tDefBTBC',                {BTall.nbc,BCall.nbt,BCall.nbt,'keeppre',0,'minBadTime',BTall.minBadTime,'minGoodTime',BTall.minGoodTime,'maskTime',BTall.maskTime},...
    'prename','a_i_','runto', 1);

% % ICA
% rmvart = 1;
% npc = 30;
% nameica = sprintf('ica%d_',npc);
% filename = sprintf('i_pca%dwtica%d_',npc,rmvart);
% eega_RunAll( 'is_a_fh2e-01_fl40_Session*.set',... 
%             fullfile(Pprp, Pdata, 'art'),...
%             fullfile(Pprp, Pdata, 'art'),...
%             'eega_pcawtica',  {'icaname',nameica,'filthighpass', 1, 'filtlowpass', 40, 'npc', npc, 'level', 6, 'threshtype', 'xlevel', 'applymara',1, 'usealphaband', 0,'rmvart',rmvart},...
%             'eega_tInterpSpatialEEG', {Int.Spl.p,'pneigh',Int.Spl.pneigh},...
%             'prename',filename,'runto', 2);


%% ------------------------------------------------------------------------
%% EPOCH AND OBTAIN THE ERP

InputFolder = fullfile(Path2Data, 'art'); 
OutputFolder = fullfile(Path2Data, 'erp'); 

ex_parameters_erp   % the parameters 
filt_highpass_ERP = 1;
filt_lowpass_ERP  = 15;
minphase = 0;

eega_RunAll( 'a_i_is_a_fh2e-01_fl40_Session*.set',...
    InputFolder,...
    OutputFolder,...
    'eega_latencyevent',        {'DIN1', {'Tw'}, [1 1]},...
    'eega_removeevent',         {'DIN1',  [], 'all'},...
    'pop_eegfiltnew',           {filt_highpass_ERP, [], [], 0, [], [], minphase},...
    'eega_epoch',               {{'Tw'}, OPT.epoch.tw},...
    'eega_tDefBTBC',            {BTep.nbc,BCep.nbt,BCall.nbt,'keeppre',1,'minBadTime',BTep.minBadTime,'minGoodTime',BTep.minGoodTime,'maskTime',BTep.maskTime},...
    'eega_tInterpSpatialEEG',   {Int.Spl.p,'pneigh', Int.Spl.pneigh},...
    'eega_tArtifacts',          {ArtMot2, 'FilterDo', 1, 'KeepRejPre', 1},...
    'eega_tDefBTBC',            {BTep.nbc,BCep.nbt,BCall.nbt,'keeppre',1,'minBadTime',BTep.minBadTime,'minGoodTime',BTep.minGoodTime,'maskTime',BTep.maskTime},...
    'eega_tDefBEbaddata',       {DefBEa,'where',DefBEa.where,'keeppre',0,'plot', 0},...
    'eega_tDefBEdistT',         {DefBEdT.limMean, DefBEdT.limMax,'where',DefBEdT.where, 'maxloops', DefBEdT.maxloops, 'keeppre',1, 'plot', 0, 'savefigure', 0},...
    'eega_tDefBEdistE',         {DefBEdE.limMean, DefBEdE.limMax,'where',DefBEdE.where, 'maxloops', DefBEdE.maxloops, 'keeppre',1, 'plot', 0, 'savefigure', 0},...
    'pop_eegfiltnew',           {[], filt_lowpass_ERP, [], 0, [], [], minphase},...
    'eega_refavg',              {},...
    'eega_normalization',       {'epochs',OPT.norm.epochs,'electrodes',OPT.norm.electrodes,'latency',OPT.norm.latency,'mean',OPT.norm.mean,'sd',OPT.norm.sd,'BadData',OPT.norm.baddata},...
    'eega_rmbaseline',          {OPT.bl.tw},...
    'eega_definefactors',       {{'eventCnd'}},...
    'eega_rmvbadepochs',        {},...
    'eega_avgdatabyfactors',    {{'eventCnd'}, 'dim2avg', 3},...
    'prename', 'avg_e_', 'saveformat', 'set', 'runto',1);

        
%% GRAN AVERAGE
Filenames = 'avg_e_a_i_is_a_fh2e-01_fl40_Session*.set';
InputFolder = fullfile(Path2Data, 'erp'); 

%merge the data of all subjects in one structure
EEGavg = eega_MergeData( Filenames, InputFolder,'dim2cat',3,'IncSbj',Sbj.inc);
%compute the garna average
EEGgavg = eega_avgdatabyfactors(EEGavg, {'eventCnd'});



        
