%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This code exemplifies how to preprocess continuos EEG data using APICE
% 
% Data is organized in one folder per subject where all the pre-processing
% steps are saved
%
% Ana Fló, December 2022
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear, close all
restoredefaultpath
clc

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PATHS
%
% Specify the paths to the different relevant folders
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Folder where EEGLAB is:
Path2EEGLAB = 'C:\Users\anafl\Documents\MATLAB\eeglab2022.1';
% Folder where the function for APICE are:
Path2APICE = 'C:\Users\anafl\Documents\GitHub\eeg_preprocessing';
% Folder where iMARA is:
Path2iMARA = 'C:\Users\anafl\Documents\MATLAB\iMARA-main';

% Folder where the main scripts are:
Path0 = 'C:\Users\anafl\Documents\GitHub\eeg_preprocessing\examples\example_CuttingEEG';
% Folder where the scripts with the parameters are:
Path2Parameters = fullfile(Path0, 'parameters');
% Folder where the data is:
Path2Data = fullfile(Path0, 'DATA');
% File with the hannels layout 
filechanloc = fullfile(Path0,'ElectrodesLayout','GSN-HydroCel-128.sfp');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% ADD TOOLBOXES AND PATHS TO USEFUL FOLDERS
%
% Add to the path the required toolboxes
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Add EEGLAB to the path
cd(Path2EEGLAB)
eeglab
close all

% Add the functions for APICE (https://github.com/neurokidslab/eeg_preprocessing)
addpath(genpath(Path2APICE))

% Add iMARA (https://github.com/Ira-marriott/iMARA/tree/main)
addpath(genpath(Path2iMARA))

% Add the path to the folder with the parameters
addpath(Path2Parameters)

% Got to the path where the main scripts are
cd(Path0)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PARAMETERS
%
% Define all the required parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% .........................................................................
% Raw files names
% .........................................................................
rawfiles = 'raw_*.set';

% .........................................................................
% Parameters dealing with events 
% .........................................................................
do_arreangeevents = 1; % run (1) or not (0)
Ppp.events = ex2_Ppp_Events;

% .........................................................................
% Parameters for filtering
% .........................................................................
Ppp.filt = ex2_Ppp_Filtering;

% .........................................................................
% Parameters for artifacts detection
% .........................................................................
% Algorithms to detect bad electrodes
Ppp.Art.BadEl = ex2_Ppp_Art_BadEl;
% Algorithms to detect jumps in the signal
Ppp.Art.Jump = ex2_Ppp_Art_Jump;
% Algorithms to detect motion artifacts
Ppp.Art.Mot1 = ex2_Ppp_Art_Mot1;
% Algorithms to detect motion artifacts
Ppp.Art.Mot2 = ex2_Ppp_Art_Mot2;

% .........................................................................
% Parameters for transient artifacts interpolation using target PCA
% .........................................................................
Ppp.Int.pca = ex2_Ppp_Int_tPCA;

% .........................................................................
% Parameters for artifacts interpolation using spherical spline
% .........................................................................
Ppp.Int.spl = ex2_Ppp_Int_Spl;

options_interspatialsegments = {...
    Ppp.Int.spl.p,...
    'pneigh', Ppp.Int.spl.pneigh,...
    'splicemethod', Ppp.Int.spl.splicemethod,...
    'mingoodtime', Ppp.Int.spl.minGoodTime,...
    'minintertime', Ppp.Int.spl.minInterTime,...
    'masktime', Ppp.Int.spl.maskTime};

options_targetPCA = {...
    Ppp.Int.pca.nSV,...
    Ppp.Int.pca.vSV,...
    'maxTime', Ppp.Int.pca.maxTime,...
    'maskTime', Ppp.Int.pca.maskTime,...
    'splicemethod', Ppp.Int.pca.splicemethod};

% .........................................................................
% Parameters to define Bad Times (BT) and Bad Channels (BC) 
% .........................................................................
Ppp.BTBC = ex2_Ppp_DefBTBC;

options_BTBC = {...
    Ppp.BTBC.BT.nbc,...
    Ppp.BTBC.BC.nbt,...
    Ppp.BTBC.BC.nbt,...
    'minBadTime', Ppp.BTBC.BT.minBadTime,...
    'minGoodTime', Ppp.BTBC.BT.minGoodTime,...
    'maskTime', Ppp.BTBC.BT.maskTime,...
    'keeppre', 0};

% .........................................................................
% Parameters for W-ICA
% .........................................................................
Ppp.ica = ex2_Ppp_wICA;
do_applyICA = 0; % run (1) or not (0)

options_ica = {...
    'filthighpass',Ppp.ica.filthighpass,...
    'filtlowpass', Ppp.ica.filtlowpass,...
    'npc', Ppp.ica.npc,...
    'classifyIC', Ppp.ica.classifyIC,...
    'classifyICfun', Ppp.ica.classifyICfun,...
    'changelabelch',Ppp.ica.changelabelch,...
    'labelch',Ppp.ica.labelch,...
    'saveica',Ppp.ica.saveica,...
    'icaname',Ppp.ica.icaname,...
    'icapath',Ppp.ica.icapath};

% .........................................................................
% Plotting
% .........................................................................
do_plotrejection = 0; % run (1) or not (0)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PRE-PROCESSING
%
% Run the pre-processing for all subjects
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


eega_RunAll_BIDS(...
    rawfiles,...
    Path2Data,...
    'pop_chanedit',{'load', {filechanloc 'filetype' 'autodetect'}},...
    'eeg_checkset', {},...
    'eega_demean', {},...
    'eega_importinfoevents', {[],Ppp.events.import.ev0},...
    'eega_latencyevent', {Ppp.events.corrlatencies.ev(1).event2, Ppp.events.corrlatencies.ev(1).event1},...
    'eega_latencyevent', {Ppp.events.corrlatencies.ev(2).event2, Ppp.events.corrlatencies.ev(2).event1},...
    'eega_latencyevent', {Ppp.events.corrlatencies.ev(3).event2, Ppp.events.corrlatencies.ev(3).event1},...
    'eega_removeevent', {Ppp.events.rmv.ev},...
    'pop_eegfiltnew', {[], Ppp.filt.lowpass,  [], 0, [], [], 0},...
    'pop_eegfiltnew', {Ppp.filt.highpass, [], [], 0, [], [], 0},...
    'pop_eegfiltnew', {Ppp.filt.notch(1), Ppp.filt.notch(2), [], 1, [], [], 0},...
    'eega_tArtifacts', {Ppp.Art.BadEl, 'KeepRejPre', 1},...
    'eega_tArtifacts', {Ppp.Art.Mot1, 'KeepRejPre', 1},...
    'eega_tArtifacts', {Ppp.Art.Jump, 'KeepRejPre', 1},...
    'eega_tDefBTBC', options_BTBC,...
    'eega_tTargetPCAxElEEG', options_targetPCA,...
    'eega_demean', {},...
    'pop_eegfiltnew', {Ppp.filt.highpass, [], [], 0, [], [], 0},...
    'eega_tDefBTBC', options_BTBC,...
    'eega_tInterpSpatialSegmentEEG', options_interspatialsegments,...
    'eega_demean', {},...
    'pop_eegfiltnew', {Ppp.filt.highpass, [], [], 0, [], [], 0},...
    'eega_tInterpSpatialEEG', {Ppp.Int.spl.p, 'pneigh', Ppp.Int.spl.pneigh},...
    'eega_tArtifacts', {Ppp.Art.Mot2, 'KeepRejPre', 1},...
    'eega_tDefBTBC', options_BTBC,...
     'prename','prp_','runto', 1);

%     'eega_pcawtica', options_ica,...
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% REPORT
%
% Print a preprocessing report for all the subjetcs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SBJs_prp = eega_getfilesinfolders(Path2Data, 'prp_raw_*.set');

T = eega_printsummary(SBJs_prp, Path2Data, [], [], 0);

